---
# Get keys from CyberArk
- hosts: local_machine
  connection: local
  gather_facts: true
    
  tasks:
  - name: Get SSH Keys for each host in inventory
    include_tasks: get_ssh_keys.yml
    with_items:
      - "{{groups['AWS']}}"
    loop_control:
      loop_var: machine_item

# Start work on machines
- hosts: AWS
  gather_facts: false

  vars:
    ansible_ssh_private_key_file: "{{ playbook_dir }}/{{inventory_hostname}}.pem"

  tasks:
    - name: apt update
      become: true 
      apt:
        name: aptitude
        force_apt_get: yes 
    - name: ensure nginx is at the latest version
      become: true
      apt: 
        name: nginx 
        state: latest
        update_cache: yes
    - name: start nginx
      become: true
      service:
          name: nginx
          state: started
    - name: Create a directory if it does not exist
      become: true
      file:
        path: "{{item}}"
        state: directory
      with_items:
        - '/var/www/html/'
        - '/var/www/html/images/'
    - name: Copy random index.html
      become: true
      copy:
        src: "{{ playbook_dir }}/nginx_web/index.{{item}}.html"
        dest: '/var/www/html/index.html'
      with_random_choice:
        - yoda
        - r2d2
        - bb8
        - c3po
    - name: Copy images
      become: true
      copy:
        src: "{{ playbook_dir }}/nginx_web/images/{{item}}"
        dest: "/var/www/html/images/{{item}}"
      with_items:
        - 'yoda.webp'
        - 'r2d2.gif'
        - 'bb8.webp'
        - 'c3po.webp'


# Remove ssh keys post execution
- hosts: local_machine
  connection: local
  gather_facts: true
    
  tasks:
  - name: Get SSH Keys for each host in inventory
    include_tasks: del_ssh_keys.yml
    with_items:
      - "{{groups['AWS']}}"
    loop_control:
      loop_var: machine_item
